version: '3.8'

services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6db
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - k6-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    networks:
      - k6-network
  k6:
    image: grafana/k6:latest
    volumes:
      - ./scripts:/scripts
      - ./utils:/utils  
      - ./config:/config  
      - ./results:/results
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6db
      - K6_JSON_OUTPUT=/results/result.json  # Xuất JSON report
    command: run /scripts/api/get-post.js  # Cập nhật đường dẫn đến file get-post.js
    depends_on:
      - influxdb
    networks:
      - k6-network  

volumes:
  influxdb-data:
  grafana-data:

networks:
  k6-network:
    driver: bridge